FROM mhart/alpine-node:8

WORKDIR app
ENV HOME="/app"

COPY . .

ENV NODE_ENV production
RUN yarn install

# Use non-root user to run the server
RUN adduser -D normal_user
USER normal_user

# Expose port for the node server, ignored by Heroku
EXPOSE 8000

CMD ["yarn", "run", "start"]