FROM mhart/alpine-node:9

WORKDIR api
ENV HOME="/api"

COPY package.json .
COPY yarn.lock .

ENV NODE_ENV production
RUN yarn

COPY . .

# Expose port for the node server, ignored by Heroku
EXPOSE 8000
